artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Govardhan211103/DataforAlg/main/churn.csv
  local_data_file: artifacts/data_ingestion/data.csv
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data.csv 
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv
  train_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv

model_trainer:
  root_dir: artifacts/model
  train_data_path: artifacts/data_transformation/train_data.csv
  test_data_path: artifacts/data_transformation/test_data.csv
  model_path: artifacts/model/model.joblib
  